apiVersion: apps/v1
kind: Deployment
metadata:
  name: folder-service-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: folder-service-server
  template:
    metadata:
      labels:
        component: folder-service-server
    spec:
      containers:
        -
          name: folder-service-backend
          image: d0rka/folder-service-backend
          ports:
            -
              containerPort: 3000
          env:
            -
              name: PGHOST
              value: postgres-cluster-ip-service
            -
              name: PGUSER
              value: postgres
            -
              name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            -
              name: PGDATABASE_DEVELOPMENT
              value: folder-service_development
            -
              name: PGDATABASE_TEST
              value: folder-service_test
            -
              name: PGDATABASE_PRODUCTION
              value: folder-service_production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: folder-service-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        -
          name: folder-service-frontend
          image: d0rka/folder-service-frontend
          ports:
            -
              containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        -
          name: postgres-storage
          persistentVolumeClaim:
            claimName: folder-service-database-pvc
      containers:
        -
          name: postgres
          image: postgres
          ports:
            -
              containerPort: 5432
          volumeMounts:
            -
              name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            -
              name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
